#!/bin/python
import gw4xxx_flask.app.default_config as defCfg
import json
import os.path
import pathlib

print("FlaskOnHAL: create config file")

pathlib.Path(defCfg.serviceFile).parents[0].mkdir(parents=True, exist_ok=True)

with open(defCfg.serviceFile,"w") as f:
    f.write(json.dumps(defCfg.defaultService, indent=4))
        
